# Generated by Django 5.1.6 on 2025-02-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='inventory',
            field=models.CharField(max_length=100),
        ),
    ]
