# Generated by Django 5.1.6 on 2025-02-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('contractor', 'Contractor'), ('employee', 'Employee'), ('vendor', 'Vendor'), ('supplier', 'Supplier')], max_length=20),
        ),
    ]
