# Generated by Django 5.1.6 on 2025-02-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
