# Generated by Django 5.1.6 on 2025-02-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='user',
        ),
        migrations.AddField(
            model_name='contractor',
            name='address',
            field=models.TextField(blank=True, default='NA'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contractor',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='contractor',
            name='phone',
            field=models.CharField(blank=True, default=12345, max_length=15),
        ),
    ]
